import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "./Providers";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";
import Provider from "./сontext/Provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Phrasal Verbs App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider>
          <Provider>
            <Navbar />
            <div className="min-h-[calc(100vh-184px)] p-8">
              {children}
            </div>
            <Footer />
          </Provider>
        </AuthProvider>
      </body>
    </html>
  );
}
